# Generated by Django 2.1.5 on 2019-02-10 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0002_auto_20190208_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
