# Generated by Django 2.1.5 on 2019-02-11 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GRsystem', '0005_auto_20190210_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch', models.CharField(max_length=200, null=True)),
                ('Type_of_complaint', models.CharField(choices=[(1, 'ClassRoom'), (2, 'Teacher'), (3, 'Management'), (4, 'School'), (5, 'Other')], default=None, max_length=1)),
                ('Description', models.TextField(max_length=4000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
