# Generated by Django 2.1.5 on 2019-02-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0012_complaint_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.IntegerField(choices=[(1, 'Solved'), (2, 'Pending')], default=1),
        ),
    ]
