# Generated by Django 2.1.5 on 2019-02-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0014_auto_20190212_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='Subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
