# Generated by Django 2.1.5 on 2019-02-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0019_auto_20190216_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_user',
            field=models.CharField(default='s', max_length=20),
        ),
    ]
