# Generated by Django 2.1.5 on 2019-02-23 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0022_auto_20190223_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type_user',
            field=models.CharField(choices=[('student', 'student'), ('grievance', 'grievance')], default='student', max_length=20),
        ),
    ]
