# Generated by Django 2.1.5 on 2019-03-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0026_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
