# Generated by Django 2.2 on 2019-04-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0028_auto_20190325_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Time',
            field=models.DateField(auto_now=True),
        ),
    ]
