# Generated by Django 2.2 on 2019-05-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0029_auto_20190430_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Branch',
            field=models.CharField(choices=[('ComputerScience', 'ComputerScience'), ('InformationScience', 'InformationScience'), ('Electronics and Communication', 'Electronics and Communication'), ('Mechanical', 'Mechanical')], max_length=200),
        ),
    ]
