# Generated by Django 2.2 on 2019-05-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0030_auto_20190508_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='Branch',
        ),
        migrations.AddField(
            model_name='profile',
            name='Branch',
            field=models.CharField(choices=[('ComputerScience', 'ComputerScience'), ('InformationScience', 'InformationScience'), ('Electronics and Communication', 'Electronics and Communication'), ('Mechanical', 'Mechanical')], default='ComputerScience', max_length=20),
        ),
    ]
