# Generated by Django 2.2 on 2019-05-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0031_auto_20190508_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('Canara', 'Canara')], max_length=7),
        ),
    ]
