# Generated by Django 2.2 on 2019-11-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRsystem', '0033_auto_20190508_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='collegename',
            field=models.CharField(choices=[('College1', 'College1'), ('College2', 'College2')], max_length=7),
        ),
    ]
